name : workflow

on : 
    push:
       branches:
         - main
    pull_request:
       branches:
          - main
    workflow_dispatch:
      
jobs:
  hello:
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name : hello 
        run : echo "hello"
        shell : bash
    
  goodbye: 
       runs-on : ubuntu-latest
       steps: 
          - name : goodbye
            run: echo "bye"
            shell : bash
